version: '3.3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: aa
      MYSQL_USER: bb
      MYSQL_PASSWORD: ab
    ports:
      - "3306:3306"

