version: '3.3'
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: aa
      MYSQL_USER: aa
      MYSQL_PASSWORD: aa
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

network:
  anetwork: